=== binazon/angular/docs/assets/target/classes/global/schema/inventoryConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="inventoryConfig" xmlns=""
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
	<xs:element name="inventoryTables" msdata:IsDataSet="true"
		msdata:Locale="en-US">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="inventoryVersion" type="xs:integer" />
				<xs:element name="openStatVersion" type="xs:string" />
				<xs:element name="reportingGroupTable">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="attribute" minOccurs="1" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Attribute to export for the ReportingGroup
										table</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Attribute name to export</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="type" type="xs:string" use="optional"
										default="VARCHAR(130)">
										<xs:annotation>
											<xs:documentation>Attribute type to export (if needed)
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="default" type="xs:string" use="optional">
										<xs:annotation>
											<xs:documentation>Default attribute value to export (if
												needed)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="reportingEntityTable">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="attribute" minOccurs="1" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Attribute to export for the current entity
										table</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Attribute name to export</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="type" type="xs:string" use="optional"
										default="VARCHAR(130)">
										<xs:annotation>
											<xs:documentation>Attribute type to export (if needed)
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="default" type="xs:string" use="optional">
										<xs:annotation>
											<xs:documentation>Default attribute value to export (if
												needed)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="listAttribute" minOccurs="0"
								maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Attribute list to export for the current
										entity table</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="parameter" minOccurs="0"
											maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Item in attribute list to export for the
													current entity table</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>Item name in the attribute list to
															export for the current entity table</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Attribute list name</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="link" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Link to export for the current entity
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="linkAttribute" minOccurs="0"
											maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Link attribute to export
												</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>Name of the link attribute to export
														</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="type" type="xs:string" use="optional"
													default="VARCHAR(130)">
													<xs:annotation>
														<xs:documentation>Type of the link attribute to export (if
															needed)</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Name of the link to export
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="target" type="xs:string" use="optional">
										<xs:annotation>
											<xs:documentation>Target of the link to export (for complex
												type)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="type" use="required">
										<xs:annotation>
											<xs:documentation>Type of the link to export
											</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="single" />
												<xs:enumeration value="complex" />
												<xs:enumeration value="parent" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="filter" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Filter (i.e subtype) to export
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Name of the filter to export
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="type" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Type of the entity to export
								</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== binazon/angular/docs/assets/target/arbrrt/WEB-INF/classes/global/inventory/inventoryConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventoryTables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/inventoryConfig.xsd">
	<inventoryVersion>19</inventoryVersion>
	<openStatVersion>G21R01C00</openStatVersion>
	<reportingGroupTable>
		<attribute name="EQUIPMENT_CPU_T1" type="INTEGER" default="1"/>
		<attribute name="EQUIPMENT_CPU_T2" type="INTEGER" default="50"/>
		<attribute name="EQUIPMENT_MEMORY_T1" type="INTEGER" default="1"/>
		<attribute name="EQUIPMENT_MEMORY_T2" type="INTEGER" default="50"/>
		<attribute name="PHYSICAL_CONNECTION_WAN_T1" type="INTEGER" default="1"/>
		<attribute name="PHYSICAL_CONNECTION_WAN_T2" type="INTEGER" default="75"/>
		<attribute name="PHYSICAL_CONNECTION_LAN_T1" type="INTEGER" default="1"/>
		<attribute name="PHYSICAL_CONNECTION_LAN_T2" type="INTEGER" default="75"/>
		<attribute name="PHYSICAL_CONNECTION_CPU_T1" type="INTEGER" default="1"/>
		<attribute name="PHYSICAL_CONNECTION_CPU_T2" type="INTEGER" default="50"/>
		<attribute name="PHYSICAL_CONNECTION_MEM_T1" type="INTEGER" default="1"/>
		<attribute name="PHYSICAL_CONNECTION_MEM_T2" type="INTEGER" default="50"/>
		<attribute name="ATMXDSL_T1" type="DOUBLE" default="1"/>
		<attribute name="ATMXDSL_T2" type="DOUBLE" default="100"/>
		<attribute name="ATMVLAN_T1" type="DOUBLE" default="1"/>
		<attribute name="ATMVLAN_T2" type="DOUBLE" default="75"/>
		<attribute name="DIMCVP_T1" type="DOUBLE" default="1"/>
		<attribute name="DIMCVP_T2" type="DOUBLE" default="75"/>
		<attribute name="LOGICALCONNECT_T1" type="INTEGER"/>
		<attribute name="LOGICALCONNECT_T2" type="INTEGER"/>
		<attribute name="NCONNECT_T1" type="INTEGER" default="5"/>
		<attribute name="NCONNECT_T2" type="INTEGER" default="75"/>
		<attribute name="NCONNECT_T3" type="INTEGER" default="0"/>
		<attribute name="COS1_T1" type="INTEGER" default="1"/>
		<attribute name="COS1_T2" type="INTEGER" default="50"/>
		<attribute name="COS2_T1" type="INTEGER" default="1"/>
		<attribute name="COS2_T2" type="INTEGER" default="50"/>
		<attribute name="COS3_T1" type="INTEGER" default="1"/>
		<attribute name="COS3_T2" type="INTEGER" default="60"/>
		<attribute name="COS4_T1" type="INTEGER" default="1"/>
		<attribute name="COS4_T2" type="INTEGER" default="30"/>
		<attribute name="COS5_T1" type="INTEGER" default="1"/>
		<attribute name="COS5_T2" type="INTEGER" default="10"/>
		<attribute name="COS6_T1" type="INTEGER" default="1"/>
		<attribute name="COS6_T2" type="INTEGER" default="50"/>
		<attribute name="OriginAccessLoadRateHighThreshold" type="INTEGER"/>
		<attribute name="OriginAccessLoadRateLowThreshold" type="INTEGER"/>
		<attribute name="OriginAccessLoadRateBetweenLowHighThreshold" type="INTEGER"/>
		<attribute name="DestAccessLoadRateHighThreshold" type="INTEGER"/>
		<attribute name="DestAccessLoadRateLowThreshold" type="INTEGER"/>
		<attribute name="DestAccessLoadRateBetweenLowHighThreshold" type="INTEGER"/>
		<attribute name="VoiceRTDDest" type="INTEGER"/>
		<attribute name="VoiceRTDOrig" type="INTEGER"/>
		<attribute name="OriginLogicalConnectionLoadRateBeyondHighSpeedHighThreshold" type="INTEGER" default="70"/>
		<attribute name="OriginLogicalConnectionLoadRateBeneathLowSpeedHighThreshold" type="INTEGER" default="30"/>
		<attribute name="OriginLogicalConnectionLoadRateBetweenLowSpeedAndHighSpeedHighThreshold" type="INTEGER" default="50"/>
		<attribute name="DestLogicalConnectionLoadRateBeyondHighSpeedHighThreshold" type="INTEGER" default="70"/>
		<attribute name="DestLogicalConnectionLoadRateBeneathLowSpeedHighThreshold" type="INTEGER" default="30"/>
		<attribute name="DestLogicalConnectionLoadRateBetweenLowSpeedAndHighSpeedHighThreshold" type="INTEGER" default="50"/>
		<attribute name="VoiceDestLogicalConnectionLoadRateHighThreshold" type="INTEGER" default="100"/>
		<attribute name="VoiceOrigLogicalConnectionLoadRateHighThreshold" type="INTEGER" default="100"/>
		<attribute name="SlaLogicalConnectionLowSpeedThreshold" type="BIGINT" default="1000"/>
		<attribute name="SlaLogicalConnectionHighSpeedThreshold" type="BIGINT" default="10000"/>		
		<attribute name="OriginLogicalConnectionLoadRateEmissionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="OriginLogicalConnectionLoadRateReceptionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="OriginVoiceCoSLoadRateEmissionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="OriginVoiceCoSLoadRateReceptionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="EndLogicalConnectionLoadRateEmissionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="EndLogicalConnectionLoadRateReceptionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="EndVoiceCoSLoadRateEmissionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="EndVoiceCoSLoadRateReceptionThresholdJitter2" type="INTEGER" default="90"/>
		<attribute name="OriginLogicalConnectionLoadRateEmissionThresholdJitter3" type="INTEGER" default="90"/>
		<attribute name="OriginLogicalConnectionLoadRateReceptionThresholdJitter3" type="INTEGER" default="90"/>
		<attribute name="EndLogicalConnectionLoadRateEmissionThresholdJitter3" type="INTEGER" default="90"/>
		<attribute name="EndLogicalConnectionLoadRateReceptionThresholdJitter3" type="INTEGER" default="90"/>
		<attribute name="OriginPhysicalConnectionLoadRateEmissionAndReceptionThresholdJitter4" type="INTEGER" default="100"/>
		<attribute name="Global_Volumetry_Choice" type="INTEGER" default="4"/>
		<attribute name="TimeSlotStartMeeting" type="INTEGER"/>
		<attribute name="TimeZoneCTSman"/>
		<attribute name="VersionCTSman"/>
		<attribute name="Co2CarCoef" type="DOUBLE"/>
		<attribute name="CarThreshold" type="INTEGER"/>
		<attribute name="Co2RailCoef" type="DOUBLE"/>
		<attribute name="RailThreshold" type="INTEGER"/>
		<attribute name="Co2AirShortCoef" type="DOUBLE"/>
		<attribute name="AirShortThreshold" type="INTEGER"/>
		<attribute name="Co2AirLongCoef" type="DOUBLE"/>
		<attribute name="CdrMinDuration" type="INTEGER"/>
		<attribute name="CdrMaxDuration" type="INTEGER"/>
		<attribute name="ANSWER_RATIO"/>
		<attribute name="NETWORK_EFFICIENCY_RATIO"/>
		<attribute name="BLOCKING_FACTOR"/>
		<attribute name="SlaSpeedLowThreshold" type="BIGINT"/>
		<attribute name="SlaSpeedHighThreshold" type="BIGINT"/>
		<attribute name="NB_DAYS_INACTIVE" type="INTEGER" default="14"/>
		<attribute name="NB_DAYS_OBSOLETE" type="INTEGER" default="31"/>
		<attribute name="DISPLAY_ALL_COS_BB" type="BOOLEAN" default="false"/>
		<attribute name="VOICE_EQUIPMENT_CPU_T1" type="INTEGER" default="0"/>
		<attribute name="VOICE_EQUIPMENT_CPU_T2" type="INTEGER" default="50"/>
		<attribute name="VOICE_EQUIPMENT_MEMORY_T1" type="INTEGER" default="0"/>
		<attribute name="VOICE_EQUIPMENT_MEMORY_T2" type="INTEGER" default="50"/>
		<attribute name="VOICE_EQUIPMENT_DISK_T1" type="INTEGER" default="0"/>
		<attribute name="VOICE_EQUIPMENT_DISK_T2" type="INTEGER" default="50"/>
		<attribute name="VOICE_CROSSING_DURATION" type="INTEGER" default="30"/>
		<attribute name="VOICE_INTERFACE_FAILURE_RATE_T1" type="INTEGER" default="1"/>
		<attribute name="VOICE_INTERFACE_FAILURE_RATE_T2" type="INTEGER" default="3"/>
		<attribute name="LANGUAGE" default="English"/>
        <attribute name="capacity_management_site_capacity_threshold" type="INTEGER" default="50"/>
	</reportingGroupTable>
	<reportingEntityTable type="EQUIPMENT">
		<attribute name="domain" />
		<attribute name="manufacturer" />
		<attribute name="voice_role" />
		<attribute name="release" />
		<attribute name="type" />
		<attribute name="isShared" type="BOOLEAN" />
		<attribute name="isUbb" type="BOOLEAN" default="false" />
		<attribute name="sareType" />
		<attribute name="address" />
		<attribute name="srv_tech_reference" />
		<attribute name="srv_cial_reference" />
		<attribute name="commercialReference" />
		<attribute name="hasStatData" type="BOOLEAN" />
		<attribute name="hasStatController" type="BOOLEAN" />
		<attribute name="cosType" />
		<attribute name="NETWORK" />
		<attribute name="cityName" />
		<attribute name="countryCode"/>
        <attribute name="countryId"/>
		<attribute name="countryName"/>
		<attribute name="cpu_max_threshold_path_perf" />
		<attribute name="customerCode" />
		<attribute name="customerName" />
		<attribute name="hardware"/>
		<attribute name="IPDSLServiceType"/>
		<attribute name="IPDSLCarrierName"/>
		<attribute name="IPDSLOfferName"/>
		<attribute name="technicalSite"/>
		<attribute name="comment" type="VARCHAR(200)"/>
		<attribute name="orchestre_label" />
        <attribute name="region" default=""/>
		<listAttribute name="addresses">
			<parameter name="type"/>
			<parameter name="value"/>
		</listAttribute>
		<link name="COUNTRY_ALPHA3" type="single"/>
		<link name="IPBXZONE" type="single"/>
		<link name="SITE" type="single"/>
		<link name="TOPO_SITE" type="single"/>
		<link name="POP_SITE" type="single"/>
		<link name="ZONE" type="single"/>
		<link name="VPN" type="single"/>
		<filter name="ANALOG-GATEWAY"/>
		<filter name="APPLI-SERVER-AC"/>
		<filter name="APPLI-SERVER"/>
		<filter name="EQUIPMENT_CLOUD"/>
		<filter name="IPT-SERVER"/>
		<filter name="MEDIA-GATEWAY"/>
		<filter name="ROUTER"/>
		<filter name="SWITCH"/>
		<filter name="SWITCH_AP"/>
		<filter name="VOICE-GATEWAY"/>
	</reportingEntityTable>
	<reportingEntityTable type="PHYSICALCONNECTION">
		<attribute name="domain" />
		<attribute name="sareType" />
		<attribute name="way" />
		<attribute name="comment" type="VARCHAR(200)"/>
		<attribute name="listIPaddress"/>
		<attribute name="srv_tech_reference" />
		<attribute name="srv_cial_reference" />
		<attribute name="hasStatData" type="BOOLEAN" />
		<attribute name="hasStatDsp" type="BOOLEAN" />
		<attribute name="hasStatVoice" type="BOOLEAN" />
        <attribute name="hasCos" type="BOOLEAN" />
        <attribute name="hasCosDifferentFromSilver" type="BOOLEAN" />
		<attribute name="cosType" />
